// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clqkndyjxvwwqvkmadbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNscWtuZHlqeHZ3d3F2a21hZGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjU1OTksImV4cCI6MjA3MDQwMTU5OX0.Z14yAJDgqtkqdH30bhW9QgfdX0SNoJr8FkzU6UKh0hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});